name: Release Production

on:
  pull_request_target:
    types: 
      - closed
    branches: 
      - main

jobs:

  main-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Repository checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.1'

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.52.2

      - name: Resolve dependencies
        run: make dependencies
        working-directory: ./server

      - name: Build
        run: make build
        working-directory: ./server

      - name: Quality
        run: make lint
        working-directory: ./server

      - name: Test
        run: make test
        working-directory: ./server

      - name: Package
        run: make package
        working-directory: ./server

      - name: Find latest rc tag
        id: find_tag
        run: |
          LATEST_RC_TAG=$(git tag -l 'rc-*' | sort -V | tail -n 1)
          echo "LATEST_RC_TAG=${LATEST_RC_TAG}" >> $GITHUB_ENV

      - name: Create new rel tag
        run: |
          NEW_TAG="rel-${LATEST_RC_TAG#rc-}"
          git tag $NEW_TAG
          git push origin $NEW_TAG
        env:
          LATEST_RC_TAG: ${{ env.LATEST_RC_TAG }}

      - name: Upload release assets
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.NEW_TAG }}.zip
          path: ./server/gobank.zip

      - name: Build Docker image
        run: |
          docker build -t $DOCKER_USERNAME/gobank:${{ env.NEW_TAG }} .
        working-directory: ./server

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push $DOCKER_USERNAME/gobank:${{ env.NEW_TAG }}
